name: sketcher
description: Sketch your ideas to life with the sketcher package. Provides the handwriting widget that allows to import\export content to SVG.
version: 1.1.5
homepage: https://github.com/glynskyi/sketcher

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ^5.0.0-nullsafety.1
  equatable: ^2.0.0-nullsafety.3
  path_parsing: ^0.2.0-nullsafety.0
  flutter_svg: ^0.20.0-nullsafety.3
  ktx: ^1.1.0-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0

flutter: